name: Release
on:
  push:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: "Create release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat <<-EOF | tee /tmp/release-note.txt
          test1
          EOF
          tar --owner=0 --group=0 --transform 's/.*\///g' -czvf openwrt-tailscale-mipsle.tar.gz  etc/ usr/
          hub release create -a "openwrt-tailscale-mipsle.tar.gz" -F /tmp/release-note.txt --draft 2.0.2
