name: Release
on:
  push:
    tags:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.0.2
      - name: "Create release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF##*/}"
          echo "${tag}" >  /tmp/release-note.txt
          tar --owner=0 --group=0 -czvf openwrt-tailscale-mipsle.tar.gz  etc/ usr/
          hub release create -a "openwrt-tailscale-mipsle.tar.gz" -F /tmp/release-note.txt --draft "${tag}"
